name: site_grupo_rmts
description: Site institucional Grupo RMTS em Flutter Web
publish_to: "none"
version: 1.0.4+1
environment:
  sdk: 3.11.3

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  webviewx_plus: ^0.5.1
  font_awesome_flutter: ^10.4.0
  webview_flutter: ^4.7.0
  dio: ^5.9.2
  flutter_dotenv: ^6.0.0
  universal_html: ^2.3.0
  mask_text_input_formatter: ^2.9.0
  signature: ^5.5.0
  intl: ^0.19.0
  shared_preferences: ^2.5.2

  # se quiser responsividade extra, dá para adicionar mais libs depois

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/logos/clientes/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
